### ISSUE TITLE
Look at removing lodash as dependency

### ISSUE THREAD

**Issue by fuller** [abhijeetNmishra/query-path#1]
Looks like _.compact is the main lodash usage right now. To decrease dependencies you could look at just implementing the function itself:
https://github.com/lodash/lodash/blob/3.10.1/lodash.src.js#L4655

Or using just that specific module from lodash:
https://www.npmjs.com/package/lodash.compact

Edit: I just looked again and realized you're also using _.isEmpty and _.each as well. Still may be worth a thought though for how to keep things as dependency-free as possible.

**Comment by abhijeetNmishra** [comment]
@ajfuller i pug lodash dependecy keeping future changes in mind. But agree, we dont need a plugin for such functionality. Removed lodash dependency :+1:
